### ISSUE TITLE
SpaceNet splits

### ISSUE THREAD

**Issue by calebrob6** [sustainlab-group/SatMAE#3]
Thanks for publishing the code for this work! I'm one of the authors of [torchgeo](https://github.com/microsoft/torchgeo) -- one of the things that we are trying to do is make it easy to have comparable results on different geospatial datasets. Do you happen to have the splits that you used for your SpaceNet experiments? I would love it if we could do something like:
```
train_ds = torchgeo.datasets.SpaceNet1(root="spacenet1/", split="satmae_train")
test_ds = torchgeo.datasets.SpaceNet1(root="spacenet1/", split="satmae_test")
```

As a note -- I _think_ the SpaceNet v2 dataset you refer to in your paper is actually SpaceNet1 (given that SpaceNet1 has 6940 images, and the paper says, "The SpaceNet v2 datasets consists of 6940 high resolution satellite images with segmentation masks for buildings, which are divided into train and test sets of 5000 and 1940 images, respectively").

(tagging @samar-khanna, @THU17cyz)

**Comment by yezhen17** [comment]
Hi @calebrob6 ,

Thanks for pointing this out! Yes, we actually used SpaceNet v1. We noticed this typo a few weeks ago and planned to fix it in NeurIPS's final camera-ready version. 

The train-test split follows the original split of the dataset.

Best,
Yezhen

**Comment by samar-khanna** [comment]
Closing issue as resolved.
