### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shelhamer** [sustainlab-group/SatMAE#4]
Thanks for sharing the code for your work 🛰🌎! Could you [add a license to it](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), such as the MIT or Apache licenses?

Clear licensing makes it more straightforward to run (and therefore cite) your research. This is especially the case for researchers in industry.

Thank you!

**Comment by samar-khanna** [comment]
Hi, we have added a license to our repo. Thanks for mentioning this!
