### ISSUE TITLE
Failed to download the Sentinel-2 corresponding images (fMoW-Sentinel) dataset,

### ISSUE THREAD

**Issue by moonboy12138** [sustainlab-group/SatMAE#6]
I've tried to download the dataset several times, but all these tries failed. Can you provide the google drive link to download the dataset?

**Comment by Jack-bo1220** [comment]
I have encountered the same problem, have you solved it?

**Comment by Jack-bo1220** [comment]
> I've tried to download the dataset several times, but all these tries failed. Can you provide the google drive link to download the dataset?

I have encountered the same problem, have you solved it? Thanks.
